[package]
name = "blog"
version = "0.1.0"
authors = ["Nicole Venner <nvenner@protonmail.ch>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus = { version = "0.7.1", features = ["router"] }
dioxus-fullstack = { version = "0.7", features = ["server", "web"] }
num-rational = "0.4.2"
pulldown-cmark = "0.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
serde_yaml = "0.9"
server_fn = "0.8.8"

[features]
default = ["web", "server"]
web = ["dioxus/web"]
server = ["dioxus/server", "dioxus/fullstack"]
desktop = ["dioxus/desktop"]
mobile = ["dioxus/mobile"]

[profile]

[profile.wasm-dev]
inherits = "dev"
opt-level = 1

[profile.server-dev]
inherits = "dev"

[profile.android-dev]
inherits = "dev"
